### ISSUE TITLE
Error: Cannot Read Geometry From KML. Cannot construct Point. z should be numeric

### ISSUE THREAD

**Issue by wisze** [mprins/dokuwiki-plugin-openlayersmap#43]
## environment

  - php version: 
  - dokuwiki version: 2022-07-31a "Igor"
  - plugin version / date:  11-11-2022
  - list of any other plugins (apart from bundled plugins): geophp, geotag, etc.
  
## expected behaviour

Display openlayers map on [my webpage](https://wiki.wisze.org/) with icons from a KML file.

## actual behaviour

Error message (see log)

### error log
2022-11-13 11:42:00	/home/w102582/domains/wisze.org/public_html/wiki/lib/plugins/geophp/vendor/funiq/geophp/src/Adapter/KML.php(74)	Exception: Cannot Read Geometry From KML. Cannot construct Point. z should be numeric
  #0 /home/w102582/domains/wisze.org/public_html/wiki/lib/plugins/geophp/vendor/funiq/geophp/src/Adapter/KML.php(53): geoPHP\Adapter\KML->geomFromText()
  #1 [internal function]: geoPHP\Adapter\KML->read()
  #2 /home/w102582/domains/wisze.org/public_html/wiki/lib/plugins/geophp/vendor/funiq/geophp/src/geoPHP.php(126): call_user_func_array()
  #3 /home/w102582/domains/wisze.org/public_html/wiki/lib/plugins/openlayersmap/StaticMap.php(275): geoPHP\geoPHP::load()
  #4 /home/w102582/domains/wisze.org/public_html/wiki/lib/plugins/openlayersmap/StaticMap.php(241): dokuwiki\plugin\openlayersmap\StaticMap->autoZoom()
  #5 /home/w102582/domains/wisze.org/public_html/wiki/lib/plugins/openlayersmap/helper/staticmap.php(129): dokuwiki\plugin\openlayersmap\StaticMap->getMap()
  #6 /home/w102582/domains/wisze.org/public_html/wiki/lib/plugins/openlayersmap/syntax/olmap.php(549): helper_plugin_openlayersmap_staticmap->getMap()
  #7 /home/w102582/domains/wisze.org/public_html/wiki/lib/plugins/openlayersmap/syntax/olmap.php(149): syntax_plugin_openlayersmap_olmap->getStaticOSM()
  #8 /home/w102582/domains/wisze.org/public_html/wiki/inc/parser/handler.php(279): syntax_plugin_openlayersmap_olmap->handle()
  #9 /home/w102582/domains/wisze.org/public_html/wiki/inc/Parsing/Lexer/Lexer.php(270): Doku_Handler->plugin()
  #10 /home/w102582/domains/wisze.org/public_html/wiki/inc/Parsing/Lexer/Lexer.php(197): dokuwiki\Parsing\Lexer\Lexer->invokeHandler()
  #11 /home/w102582/domains/wisze.org/public_html/wiki/inc/Parsing/Lexer/Lexer.php(147): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens()
  #12 /home/w102582/domains/wisze.org/public_html/wiki/inc/Parsing/Parser.php(109): dokuwiki\Parsing\Lexer\Lexer->parse()
  #13 /home/w102582/domains/wisze.org/public_html/wiki/inc/parserutils.php(223): dokuwiki\Parsing\Parser->parse()
  #14 /home/w102582/domains/wisze.org/public_html/wiki/inc/parserutils.php(188): p_get_instructions()
  #15 /home/w102582/domains/wisze.org/public_html/wiki/inc/parserutils.php(510): p_cached_instructions()
  #16 /home/w102582/domains/wisze.org/public_html/wiki/inc/parserutils.php(289): p_render_metadata()
  #17 /home/w102582/domains/wisze.org/public_html/wiki/inc/common.php(246): p_get_metadata()
  #18 /home/w102582/domains/wisze.org/public_html/wiki/doku.php(97): pageinfo()
  #19 {main}

**Comment by mprins** [comment]
That seems like a bug with the KML, which is missing values for the Z of a point
```xml
<Placemark id="crc32-7b3c1562">
...
</description>
  <styleUrl>#icon</styleUrl>
  <Point><coordinates>4.829931,45.757462,</coordinates></Point>
</Placemark>
```
 which looks like it is generated using the [spatialhelper](https://github.com/mprins/dokuwiki-plugin-spatialhelper) plugin;
which should skip  adding empty Z values, but doesn't:

https://github.com/mprins/dokuwiki-plugin-spatialhelper/blob/4c284720309826e51f9e120193a976f77003e14b/helper/sitemap.php#L231-L235
