### ISSUE TITLE
Plugin throws error on clean dokuwiki install

### ISSUE THREAD

**Issue by WetenSchaap** [mprins/dokuwiki-plugin-openlayersmap#61]
## environment

  - php version: 8.2
  - dokuwiki version: 2023-04-04a "Jack Jackrum", docker container provided by linuxserver.io
  - plugin version / date: 2023-07-18
  - list of any other plugins (apart from bundled plugins): None
  
## expected behaviour

When I make a page with content:

```
====== Test ======

<olmap id="olMap" width="600px" height="400px" lat="52.0" lon="5.1" zoom="12" controls="1" baselyr="OSM" summary="This is an example map.">
52.1,5.1,60,.8,marker.png,Just a spot
</olmap>
```
A map should be shown.

## actual behaviour

An error is shown (Error: Class "geoPHP\Geometry\Point" )

## steps to reproduce actual behaviour

1. Install dokuwiki
2. Install plugin
3. Make page with olmap

### error log

```
Error: Class "geoPHP\Geometry\Point" not found/config/dokuwiki/lib/plugins/openlayersmap/StaticMap.php(268)
    #0 /config/dokuwiki/lib/plugins/openlayersmap/StaticMap.php(241): dokuwiki\plugin\openlayersmap\StaticMap->autoZoom()
    #1 /config/dokuwiki/lib/plugins/openlayersmap/helper/staticmap.php(129): dokuwiki\plugin\openlayersmap\StaticMap->getMap()
    #2 /config/dokuwiki/lib/plugins/openlayersmap/syntax/olmap.php(548): helper_plugin_openlayersmap_staticmap->getMap()
    #3 /config/dokuwiki/lib/plugins/openlayersmap/syntax/olmap.php(149): syntax_plugin_openlayersmap_olmap->getStaticOSM()
    #4 /app/www/public/inc/parser/handler.php(284): syntax_plugin_openlayersmap_olmap->handle()
    #5 /app/www/public/inc/Parsing/Lexer/Lexer.php(270): Doku_Handler->plugin()
    #6 /app/www/public/inc/Parsing/Lexer/Lexer.php(197): dokuwiki\Parsing\Lexer\Lexer->invokeHandler()
    #7 /app/www/public/inc/Parsing/Lexer/Lexer.php(147): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens()
    #8 /app/www/public/inc/Parsing/Parser.php(109): dokuwiki\Parsing\Lexer\Lexer->parse()
    #9 /app/www/public/inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse()
    #10 /app/www/public/inc/parserutils.php(198): p_get_instructions()
    #11 /app/www/public/inc/parserutils.php(525): p_cached_instructions()
    #12 /app/www/public/inc/parserutils.php(299): p_render_metadata()
    #13 /app/www/public/inc/common.php(266): p_get_metadata()
    #14 /app/www/public/doku.php(97): pageinfo()
    #15 {main}
```

**Comment by mprins** [comment]
You seem to have failed to install other required plugins notable geophp, see https://www.dokuwiki.org/plugin:openlayersmap
